### ISSUE TITLE
Add "latest" shortcut to /reports

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/w3c-api#16] opened 2015-07-09 13:32 UTC
It would be nice if /reports/{shortname}/latest was an alias to whatever is the latest known version of the said spec. Right now, it takes two hops from a shortname to the list of its WGs, and the "latest" alias would avoid that issue.

Alternatively, the description of the latest version might be in-lined in the report/{shortname} endpoint — it is after all likely to be relevant information for the API user.

**Comment by tripu** [comment] 2015-11-24 14:07
@deniak, I think that now that an API key is required, this redirection no longer works automatically:

```
$ HEAD -S https://api.w3.org/specifications/SVG11/versions/latest?apikey=[MY_KEY]
HEAD https://api.w3.org/specifications/SVG11/versions/latest?apikey=[MY_KEY]
302 Found
HEAD https://api.w3.org/specifications/SVG11/versions/20110816
401 Missing API key
```

(This is causing an error in `node-w3capi`'s test suite.)

Is this the intended behaviour? If so, in `node-w3capi` I'll have to always capture the error thrown by the redirection, append the same key to the redirected URL, and try to fetch again&hellip;

**Comment by tripu** [comment] 2015-11-24 16:25
w3c/node-w3capi#6 will fix this in `node-w3capi`.

I'll let you guys decide if this is a bug in the API or not, regardless of its (now null) impact on this particular client&hellip;

**Comment by vivienlacourba** [comment] 2015-11-26 17:09
Closing again as the issue concerning the `apiKey` parameter being dropped during redirects is discussed in #59.

**Closed by vivienlacourba** 2015-11-26 17:09 UTC
