### ISSUE TITLE
Provide link to external identity

### ISSUE THREAD

**Issue by sandhawke** [w3c/w3c-api#56] opened 2015-10-26 15:23 UTC
I'd love to do a demo for TPAC that relies on connecting W3C Users with real-world users.  That means I need the API to expose the user's URLs.   

That is, at https://www.w3.org/users/myprofile people can set things like Homepage, Github, WebID, etc.   Those should be available through the API.    When I see a list of people in a group, I should be able to click and get their homepages, right?   And authorize using their github or webid, right?

**Comment by vivienlacourba** [comment] 2015-10-28 00:32
@sandhawke those user provided links are not exposed in the API as they are today not reliable, plus from a privacy perspective we have so far not been transparent with our users on how this information will be used and in particular that we would make it publicly available.

This is something that we will add to the API once W3C implements public profiles (a project that is still desired but without any Marcom or Systeam resources assigned to it as of today).

**Comment by vivienlacourba** [comment] 2015-10-28 00:35
BTW link to services like GitHub is something we are planning to add as it has been a popular request (see: #12 )

**Comment by sandhawke** [comment] 2015-10-28 22:00
So the fear is that users might be providing homepage and github and webid links but thinking the information is only for the w3c members, or something like that?  How do you propose to solve that?   I guess you could add a check box next to the links that says "make these links public".   That sounds relatively easy, and then it would clearly be okay to add to the API when checked, right?   Any other ideas?   (That check box would be good enough for me, I guess.)

Why does this depend on a "public profiles" project?   Once you make these links available, then someone else can do a public profiles app.

**Comment by sandhawke** [comment] 2015-11-05 22:55
I've re-opening this issue with a less-urgent title since my deadline passed.  But this is still important, and it's not a question.  Applications need a way to connect W3C user accounts to other identifying information.   And it has to be two-way, with each data source linking to the other, in order to be trustworthy.    (And yes, it overlaps #12 but of course not just github)

**Comment by sandhawke** [comment] 2016-03-25 14:07
I've decided to call this a bug, since after five months I'm still unable to use this API because of this problem.   I know it doesn't look like a bug to you.     But as it is, it makes the W3C look more closed and proprietary and hard to work with than, for example, the major social silos.   And it makes some of our most valuable information, like who is in which group, largely unusable, since the identifiers for those people have no connection to anything outside W3C.

**Comment by tripu** [comment] 2016-03-25 14:16
I beg to differ. This is not a bug, IMHO. I fail to see how the lack of one specific feature (important as it may be for a subset of its user) in a tool or service makes it &ldquo;completely unusable&rdquo;.

**Comment by sandhawke** [comment] 2016-03-25 14:21
Fine, I've changed it from "completely unusable" to "largely unusable".

I don't know of a formal definition for the bug tag, but I think by many definitions this qualifies.   I also don't care what it's called, as long as it gets fixed.

**Comment by jean-gui** [comment] 2017-03-14 12:19
It is now possible to securely add external accounts by going to https://www.w3.org/users/myprofile/connectedaccounts. This information is then exposed in the API.
So far we've only allowed to connect to Github as it had a practical use case for WG work. If there are strong use cases for other services, it is possible to add them, provided that they support OAuth and are on the list at https://github.com/hwi/HWIOAuthBundle/blob/master/README.md.
Regarding exposing user links as Vivien already explained (https://github.com/w3c/w3c-api/issues/56#issuecomment-151683473) this will be looked at when the W3C public profile project gets revived. Note that those links wouldn't be reliable.

**Closed as completed by jean-gui** 2017-03-14 12:19 UTC
Labels: enhancement
